### PR TITLE
Idea 15 compatibility — PlatformDependentToolsInstaller could be app service now and appropriate implementation selected by "os" attribute

### PR DESCRIPTION
**Pull request by develar**
Method ComponentManagerEx.registerComponent was removed in IDEA 15. To support your use case I add support to specify "os" in the service configuration.

Please build and publish new version to plugin repository (https://dl.dropboxusercontent.com/u/43511007/s/idea-nginx.zip). 

IDEA 142.3304 is not yet available, but plugin repository manager check plugin updates before IDE update, so, it is better to publish plugin before official EAP. If you want, I can provide you private build.

### CODE REVIEW

**Comment by ishchenko** [comment]
Vladimir, could you please bump version in plugin.xml, add version description, update pull request, rebuild the plugin against 142.3304 and post binaries here so that I could upload it to JetBrains repo? Version should probably be like 0.1.0, as if it was a major update ;)

**Comment by arpheno** [comment]
This isnt working for me, could you check whats wrong?

**Comment by develar** [comment]
@arpheno Could you please provide more details — log file for example (Help -> Show Log in)?

**Comment by arpheno** [comment]
image
  INFO -        #com.intellij.idea.Main - IDE: PyCharm (build #PY-143.526, 27 Oct 2015 00:00) 
2015-10-29 01:15:52,050 [    840]   INFO -        #com.intellij.idea.Main - OS: Windows 8 (6.2, x86) 
2015-10-29 01:15:52,050 [    840]   INFO -        #com.intellij.idea.Main - JRE: 1.8.0_51-b16 (Oracle Corporation) 
2015-10-29 01:15:52,050 [    840]   INFO -        #com.intellij.idea.Main - JVM: 25.51-b03 (Java HotSpot(TM) Server VM) 
2015-10-29 01:15:52,081 [    871]   INFO -        #com.intellij.idea.Main - JVM Args: -Xms128m -Xmx512m -XX:MaxPermSize=250m -XX:ReservedCodeCacheSize=240m -XX:+UseConcMarkSweepGC -XX:SoftRefLRUPolicyMSPerMB=50 -ea -Dsun.io.useCanonCaches=false -Djava.net.preferIPv4Stack=true -XX:+HeapDumpOnOutOfMemoryError -XX:-OmitStackTraceInFastThrow -agentlib:yjpagent=probe_disable=*,disablealloc,disabletracing,onlylocal,disableexceptiontelemetry,delay=10000,sessionname=PyCharm50 -Djb.vmOptions=C:\Program Files (x86)\JetBrains\PyCharm 143.414\bin\pycharm.exe.vmoptions -Xbootclasspath/a:C:\Program Files (x86)\JetBrains\PyCharm 143.414\lib\boot.jar -Didea.platform.prefix=Python -Didea.no.jre.check=true -Didea.paths.selector=PyCharm50 
2015-10-29 01:15:52,376 [   1166]   INFO -        #com.intellij.idea.Main - JNA library loaded (32-bit) in 293 ms 
2015-10-29 01:15:52,395 [   1185]   INFO - penapi.util.io.win32.IdeaWin32 - Native filesystem for Windows is operational 
2015-10-29 01:15:52,414 [   1204]   INFO -        #com.intellij.idea.Main - Using "FocusKiller" library to prevent focus stealing. 
2015-10-29 01:15:53,712 [   2502]   INFO - llij.ide.plugins.PluginManager - Cannot find optional descriptor js-nashorn-support.xml 
2015-10-29 01:15:53,954 [   2744]   INFO - llij.ide.plugins.PluginManager - Cannot find optional descriptor uml-java-support.xml 
2015-10-29 01:15:54,005 [   2795]   INFO - llij.ide.plugins.PluginManager - Cannot find optional descriptor uml-properties-support.xml 
2015-10-29 01:15:54,411 [   3201]   INFO - llij.ide.plugins.PluginManager - 55 plugins initialized in 1208 ms 
2015-10-29 01:15:54,423 [   3213]   INFO - llij.ide.plugins.PluginManager - Loaded bundled plugins: AngularJS (999.999), CSS Support (143.SNAPSHOT), CVS Integration (11), CoffeeScript (2.0), Concurrency Visualiser (0.1), Database Tools and SQL (1.0), Django Database Support Integration (1.0), Docker for Python (0.1), EditorConfig (1.0), File Watchers (999.999), GNU GetText files support (*.po) (136.SNAPSHOT), Gherkin (999.999), Git Integration (8.1), GitHub (143.526), HAML (143.SNAPSHOT), HTML Tools (2.0), IDEA CORE (143.SNAPSHOT), IPython Notebook (0.1), Ini4Idea (999.999), IntelliLang (8.0), JavaScript Debugger (1.0), JavaScript Intention Power Pack (0.9.4), JavaScript Support (1.0), LESS support (143.SNAPSHOT), Perforce Integration (2.0), Puppet Support (VERSION), Python BDD support for engines, based on Gherkin (cucumber, lettuce, behave) (0.1), Python IntelliLang (VERSION), Python JavaScript Debugger Integration (VERSION), Python Localization Integration (VERSION), Python Profiler (0.1), Python ReStructureText Integration (VERSION), Python Remote Interpreter (VERSION), Python UML Diagrams (VERSION), REST Client (143.SNAPSHOT), ReStructuredText Support (136.SNAPSHOT), Remote Hosts Access (0.1), SASS support (143.SNAPSHOT), SSH Remote Run (0.1), Stylus support (999.999), Subversion Integration (1.1), Task Management (1.0), Terminal (0.1), TextMate bundles support (VERSION), UML Support (1.0), Vagrant (0.6.VERSION), hg4idea (10.0) 
2015-10-29 01:15:54,424 [   3214]   INFO - llij.ide.plugins.PluginManager - Loaded custom plugins: .ignore (1.2), BashSupport (1.5.1.143), Command Line Tool Support (142.5282), Dash (3.2.3), Docker integration (1.7.1), IdeaVim (0.41), Markdown support (8.0.0.20151023), nginx Support (0.1.0) 
2015-10-29 01:15:54,734 [   3524]  ERROR - llij.ide.plugins.PluginManager - com.intellij.ide.plugins.PluginManager$StartupAbortedException: com.intellij.diagnostic.PluginException: net.ishchenko.idea.nginx.NginxKeywordsManager PluginClassLoader[ideanginx9, 0.1.0] [Plugin: ideanginx9] 
java.lang.RuntimeException: com.intellij.ide.plugins.PluginManager$StartupAbortedException: com.intellij.diagnostic.PluginException: net.ishchenko.idea.nginx.NginxKeywordsManager PluginClassLoader[ideanginx9, 0.1.0] [Plugin: ideanginx9]
	at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:201)
	at com.intellij.idea.MainImpl$1$1$1.run(MainImpl.java:61)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:360)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: com.intellij.ide.plugins.PluginManager$StartupAbortedException: com.intellij.diagnostic.PluginException: net.ishchenko.idea.nginx.NginxKeywordsManager PluginClassLoader[ideanginx9, 0.1.0] [Plugin: ideanginx9]
	at com.intellij.ide.plugins.PluginManager.handleComponentError(PluginManager.java:240)
	at com.intellij.openapi.components.impl.PlatformComponentManagerImpl.handleInitComponentError(PlatformComponentManagerImpl.java:43)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.a(ComponentManagerImpl.java:428)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:96)
	at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:454)
	at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:446)
	at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:194)
	... 16 more
Caused by: com.intellij.diagnostic.PluginException: net.ishchenko.idea.nginx.NginxKeywordsManager PluginClassLoader[ideanginx9, 0.1.0] [Plugin: ideanginx9]
	... 23 more
Caused by: java.lang.ClassNotFoundException: net.ishchenko.idea.nginx.NginxKeywordsManager PluginClassLoader[ideanginx9, 0.1.0]
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:68)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.a(ComponentManagerImpl.java:408)
	... 20 more
2015-10-29 01:15:54,740 [   3530]  ERROR - llij.ide.plugins.PluginManager - PyCharm PY-143.526  Build #PY-143.526 
2015-10-29 01:15:54,740 [   3530]  ERROR - llij.ide.plugins.PluginManager - JDK: 1.8.0_51 
2015-10-29 01:15:54,740 [   3530]  ERROR - llij.ide.plugins.PluginManager - VM: Java HotSpot(TM) Server VM 
2015-10-29 01:15:54,741 [   3531]  ERROR - llij.ide.plugins.PluginManager - Vendor: Oracle Corporation 
2015-10-29 01:15:54,741 [   3531]  ERROR - llij.ide.plugins.PluginManager - OS: Windows 8 
2015-10-29 01:16:06,360 [  15150]   INFO -        #com.intellij.idea.Main - ------------------------------------------------------ IDE SHUTDOWN ------------------------------------------------------ 
2015-10-29 01:16:06,376 [  15166]   INFO - org.jetbrains.io.BuiltInServer - web server stopped

**Pull request merged**
