### PR TITLE
Update directives + bug fixes

### LINKED ISSUE #7: Support double quotes
Hello, first of all this module is nice.

But unfortunately, I came through an issue when trying to specify symbol repetition within a rewrite rule. For example consider the following : 

```
location /nice {
    rewrite "^/nice/([a-z0-9]{2,8})$" /foo/page?id=$1 break;
}
```

In this case, the closing curly brace after "8" will be highlighted as an issue and code reformat will consider the curly braces as a location, ending with a weird formatting.

### LINKED ISSUE #15: parsing server name doesn't allow multiple domains
The line below gives an error saying it expects one argument and found 2.

    server_name dev.asdf.com test.asdf.com;

### LINKED ISSUE #21: "Wrong number of values for server_name. Expected 1, but got 2."
For the first example at http://nginx.org/en/docs/http/server_names.html

```
server {
    listen       80;
    server_name  example.org  www.example.org;
}
```

The syntax highlighter reports an error:

> Wrong number of values for server_name. Expected 1, but got 2.

Versions:
* idea-nginx 0.0.15
* IntelliJ 13.1.4

### LINKED ISSUE #23: Support optional always parameter of add_header directive.
Please have a look at the official documentation http://nginx.org/en/docs/http/ngx_http_headers_module.html#add_header

### LINKED ISSUE #28: Support for OpenResty Syntax Hilighting and Autocomplete
Adding support for these would be nice, ;-):
https://github.com/openresty/lua-nginx-module

### LINKED ISSUE #38: Plugin does not run under IntelliJ IDEA 2016.1, Build #IU-145.258
The plugin does not run under the mentioned IDEA version.
It cannot be installed too, except by extracting the jar from the zip. But even when the jar is installed by "from disk", it does not run. It does not recognize nginx.conf files, no menu entries are created, etc.

It would be wonderful if this very useful plugin would be running again under the new version!

This is the IDEA release that was tested:
IntelliJ IDEA 2016.1
Build #IU-145.258, built on March 17, 2016
JRE: 1.8.0_76-release-b18 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

### PR DESCRIPTION
**Pull request by Deadleg**
Jar [here](https://github.com/Deadleg/idea-nginx/releases) with changelog.

I also removed the dependency on apache exec since I was admittedly too lazy to download the jar and add to classpath. This only effects the check for the nginx version, which works on linux, osx and windows from my testing.

The doc generator was deleted too since the nginx website has changed and it removes other build dependencies.

Fixes #28 
Fixes #21 
Fixes #7 
Fixes #15 
Fixes #23 

Should fix #38 #37 #27 etc. Didn't do anything different, but the build works for me in the latest intellij idea.

### CODE REVIEW

**Comment by ishchenko** [comment]
@Deadleg what is your jetbrains account? i want to add you to plugin developer list so that you can upload new builds to repo

**Comment by Deadleg** [comment]
Deadleg https://plugins.jetbrains.com/space/index?pr=&lg=Deadleg

**Comment by ishchenko** [comment]
Try to upload to https://plugins.jetbrains.com/plugin/4415?pr=idea

**Comment by Deadleg** [comment]
Uploaded. Just downloaded to my mac and it works. Cheers!

**Pull request merged**
