### PR TITLE
Idea 15 compatibility — bump version in plugin.xml and add version description

### PR DESCRIPTION
**Pull request by develar**
Binary — https://dl.dropboxusercontent.com/u/43511007/s/idea-nginx.zip.

### CODE REVIEW

**Comment by ishchenko** [comment]
Thanks, uploaded to repo

**Comment by metyl** [comment]
Looks like it is still **not** uploaded to plugins repository. Can You upload it?

**Comment by ishchenko** [comment]
Sorry, folks. Was sure i did upload it. 

Tried once again.

**Comment by mohamnag** [comment]
I think the packaging on this binary is done wrong. Trying to install it from repo does nothing and when I downloaded this binary and tried installing it directly I get "Fail to load plugin descriptor from file ..."

screen shot 2015-12-09 at 11 29 33

**Comment by renet** [comment]
It doesn't get listed in the list of installed plugins, when installing if from the repo. Can you please fix this? =)

**Comment by amittapalli** [comment]
I am unable to install the nginx plugin in web storm 11.  I tried several times but does not get installed.  Any progress on it?

**Pull request merged**
